# Generated by Django 6.0.5 on 2026-06-11 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono_whatsapp', models.CharField(help_text='Formato internacional: +573001234567', max_length=20, unique=True)),
                ('fecha_cirugia', models.DateField(help_text='Fecha de la cirugía Sugarbaker/HIPEC')),
                ('medico_responsable', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='Desactivar cuando el paciente termina el seguimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=1, help_text='Temperatura corporal en °C. Ej: 37.5', max_digits=4)),
                ('dolor_eva', models.PositiveSmallIntegerField(help_text='Escala visual análoga del 1 al 10')),
                ('volumen_drenaje_ml', models.PositiveIntegerField(blank=True, help_text='Volumen del drenaje en mililitros', null=True)),
                ('aspecto_drenaje', models.CharField(choices=[('seroso', 'Seroso'), ('hematico', 'Hemático'), ('purulento', 'Purulento'), ('fecaloide', 'Fecaloide'), ('sin_drenaje', 'Sin drenaje')], default='sin_drenaje', max_length=20)),
                ('presencia_gases', models.BooleanField(default=False, help_text='¿El paciente reportó presencia de gases?')),
                ('episodios_nauseas', models.PositiveSmallIntegerField(default=0, help_text='Número de episodios de náuseas o vómito en 24h')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('dia_postoperatorio', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='signos_sintomas.paciente')),
            ],
            options={
                'verbose_name': 'Registro Diario',
                'verbose_name_plural': 'Registros Diarios',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEPSIS', 'Fiebre — Riesgo de Sepsis'), ('FUGA_ANASTOMOTICA', 'Drenaje Anormal — Posible Fuga Anastomótica'), ('ILEO_PARALITICO', 'Sin Tránsito Intestinal — Posible Íleo Paralítico'), ('DOLOR_AGUDO', 'Dolor Agudo Incontrolable')], max_length=30)),
                ('severidad', models.CharField(choices=[('ALTA', 'Alta — Ir a urgencias'), ('MEDIA', 'Media — Llamar al médico'), ('BAJA', 'Baja — Monitorear')], max_length=10)),
                ('mensaje', models.TextField(help_text='Descripción automática generada por el alert_engine')),
                ('resuelta', models.BooleanField(default=False, help_text='El oncólogo marca esto cuando atiende la alerta')),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, help_text='Cuándo fue atendida por el médico', null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='signos_sintomas.paciente')),
                ('registro_origen', models.ForeignKey(help_text='El registro diario que disparó esta alerta', on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='signos_sintomas.registrodiario')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_alerta'],
            },
        ),
    ]
