# Generated by Django 6.0.5 on 2026-06-13 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='cantidad_drenaje',
            field=models.CharField(blank=True, choices=[('poco', 'Poco (menos de lo normal)'), ('normal', 'Normal (similar a días anteriores)'), ('mucho', 'Mucho (más de lo normal)'), ('sin_drenaje', 'No tengo drenaje')], help_text='Escala cualitativa reportada por el paciente vía WhatsApp', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='volumen_drenaje_ml',
            field=models.PositiveIntegerField(blank=True, help_text='Volumen en ml — OPCIONAL, solo si el paciente lo midió', null=True),
        ),
        migrations.CreateModel(
            name='ConversacionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INICIO', 'Inicio'), ('ESPERANDO_TEMPERATURA', 'Esperando temperatura'), ('ESPERANDO_DOLOR', 'Esperando dolor EVA'), ('ESPERANDO_ASPECTO_DRENAJE', 'Esperando aspecto del drenaje'), ('ESPERANDO_CANTIDAD_DRENAJE', 'Esperando cantidad del drenaje'), ('ESPERANDO_GASES_NAUSEAS', 'Esperando gases y náuseas'), ('COMPLETADO', 'Completado')], default='INICIO', max_length=30)),
                ('temp_temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('temp_dolor_eva', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temp_aspecto_drenaje', models.CharField(blank=True, choices=[('seroso', 'Seroso'), ('hematico', 'Hemático'), ('purulento', 'Purulento'), ('fecaloide', 'Fecaloide'), ('sin_drenaje', 'Sin drenaje')], max_length=20, null=True)),
                ('temp_cantidad_drenaje', models.CharField(blank=True, choices=[('poco', 'Poco (menos de lo normal)'), ('normal', 'Normal (similar a días anteriores)'), ('mucho', 'Mucho (más de lo normal)'), ('sin_drenaje', 'No tengo drenaje')], max_length=12, null=True)),
                ('temp_volumen_drenaje_ml', models.PositiveIntegerField(blank=True, help_text='ml extraídos del mensaje si el paciente los agregó (opcional)', null=True)),
                ('temp_presencia_gases', models.BooleanField(blank=True, null=True)),
                ('temp_episodios_nauseas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_ultimo_registro', models.DateField(blank=True, help_text='Día en que el paciente completó su último registro', null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(help_text='Cada paciente tiene una sola conversación activa con el bot', on_delete=django.db.models.deletion.PROTECT, related_name='conversacion', to='signos_sintomas.paciente')),
            ],
            options={
                'verbose_name': 'Conversación WhatsApp',
                'verbose_name_plural': 'Conversaciones WhatsApp',
            },
        ),
    ]
