# Generated by Django 6.0.5 on 2026-06-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0002_registrodiario_cantidad_drenaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipo_cirugia',
            field=models.CharField(blank=True, choices=[('sugarbaker_hipec', 'Sugarbaker / HIPEC'), ('colectomia_electiva', 'Colectomía electiva'), ('otra', 'Otra cirugía colorrectal')], help_text='Tipo de cirugía realizada — dato descriptivo para estadística e investigación futura. No afecta el alert_engine ni el flujo del bot.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_cirugia',
            field=models.DateField(help_text='Fecha de la cirugía a la que se le da seguimiento postoperatorio.'),
        ),
    ]
