# Generated by Django 6.0.5 on 2026-06-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0003_paciente_tipo_cirugia_alter_paciente_fecha_cirugia'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='temp_tiene_drenaje',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='tiene_drenaje',
            field=models.BooleanField(blank=True, help_text='¿El paciente tiene drenaje activo? null = no capturado (registros anteriores a esta versión). False = confirmado sin drenaje. True = tiene drenaje.', null=True),
        ),
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='estado',
            field=models.CharField(choices=[('INICIO', 'Inicio'), ('ESPERANDO_TEMPERATURA', 'Esperando temperatura'), ('ESPERANDO_DOLOR', 'Esperando dolor EVA'), ('ESPERANDO_TIENE_DRENAJE', 'Esperando si tiene drenaje'), ('ESPERANDO_ASPECTO_DRENAJE', 'Esperando aspecto del drenaje'), ('ESPERANDO_CANTIDAD_DRENAJE', 'Esperando cantidad del drenaje'), ('ESPERANDO_GASES_NAUSEAS', 'Esperando gases y náuseas'), ('COMPLETADO', 'Completado')], default='INICIO', max_length=30),
        ),
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='temp_aspecto_drenaje',
            field=models.CharField(blank=True, choices=[('seroso', 'Seroso'), ('hematico', 'Hemático'), ('turbio', 'Turbio'), ('purulento', 'Purulento'), ('fecaloide', 'Fecaloide'), ('sin_drenaje', 'Sin drenaje')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='aspecto_drenaje',
            field=models.CharField(choices=[('seroso', 'Seroso'), ('hematico', 'Hemático'), ('turbio', 'Turbio'), ('purulento', 'Purulento'), ('fecaloide', 'Fecaloide'), ('sin_drenaje', 'Sin drenaje')], default='sin_drenaje', max_length=20),
        ),
    ]
