# Generated by Django 6.0.5 on 2026-06-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0004_conversacionwhatsapp_temp_tiene_drenaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='temp_tolero_liquidos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='tolero_liquidos',
            field=models.BooleanField(blank=True, help_text='¿El paciente toleró líquidos sin vomitar? null = no capturado (registros anteriores a esta versión). False = no toleró. True = toleró.', null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('SEPSIS', 'Fiebre — Riesgo de Sepsis'), ('FUGA_ANASTOMOTICA', 'Drenaje Anormal — Posible Fuga Anastomótica'), ('ILEO_PARALITICO', 'Sin Tránsito Intestinal — Posible Íleo Paralítico'), ('DOLOR_AGUDO', 'Dolor Agudo Incontrolable'), ('INTOLERANCIA_ORAL', 'Intolerancia a Líquidos — Riesgo de Deshidratación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='estado',
            field=models.CharField(choices=[('INICIO', 'Inicio'), ('ESPERANDO_TEMPERATURA', 'Esperando temperatura'), ('ESPERANDO_DOLOR', 'Esperando dolor EVA'), ('ESPERANDO_TIENE_DRENAJE', 'Esperando si tiene drenaje'), ('ESPERANDO_ASPECTO_DRENAJE', 'Esperando aspecto del drenaje'), ('ESPERANDO_CANTIDAD_DRENAJE', 'Esperando cantidad del drenaje'), ('ESPERANDO_GASES_NAUSEAS', 'Esperando gases y náuseas'), ('ESPERANDO_TOLERANCIA_LIQUIDOS', 'Esperando tolerancia a líquidos'), ('COMPLETADO', 'Completado')], default='INICIO', max_length=30),
        ),
    ]
