# Generated by Django 6.0.5 on 2026-06-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0005_conversacionwhatsapp_temp_tolero_liquidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='temp_hinchazon_abdominal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='hinchazon_abdominal',
            field=models.CharField(blank=True, choices=[('nada', 'Nada'), ('algo', 'Algo'), ('mucho', 'Mucho')], help_text='Nivel de hinchazón/distensión abdominal auto-reportado. null = no capturado. Se evalúa por empeoramiento entre días.', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='estado',
            field=models.CharField(choices=[('INICIO', 'Inicio'), ('ESPERANDO_TEMPERATURA', 'Esperando temperatura'), ('ESPERANDO_DOLOR', 'Esperando dolor EVA'), ('ESPERANDO_TIENE_DRENAJE', 'Esperando si tiene drenaje'), ('ESPERANDO_ASPECTO_DRENAJE', 'Esperando aspecto del drenaje'), ('ESPERANDO_CANTIDAD_DRENAJE', 'Esperando cantidad del drenaje'), ('ESPERANDO_GASES_NAUSEAS', 'Esperando gases y náuseas'), ('ESPERANDO_HINCHAZON', 'Esperando hinchazón abdominal'), ('ESPERANDO_TOLERANCIA_LIQUIDOS', 'Esperando tolerancia a líquidos'), ('COMPLETADO', 'Completado')], default='INICIO', max_length=30),
        ),
    ]
