# Generated by Django 6.0.5 on 2026-06-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0007_conversacionwhatsapp_temp_frecuencia_cardiaca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='temp_frecuencia_respiratoria',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='frecuencia_respiratoria',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Frecuencia respiratoria en rpm. null = no capturado. SOLO DASHBOARD — no genera alerta (Outersterp 2025: 77% de falsas alertas provenían del sensor de FR).', null=True),
        ),
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='estado',
            field=models.CharField(choices=[('INICIO', 'Inicio'), ('ESPERANDO_TEMPERATURA', 'Esperando temperatura'), ('ESPERANDO_DOLOR', 'Esperando dolor EVA'), ('ESPERANDO_TIENE_DRENAJE', 'Esperando si tiene drenaje'), ('ESPERANDO_ASPECTO_DRENAJE', 'Esperando aspecto del drenaje'), ('ESPERANDO_CANTIDAD_DRENAJE', 'Esperando cantidad del drenaje'), ('ESPERANDO_GASES_NAUSEAS', 'Esperando gases y náuseas'), ('ESPERANDO_HINCHAZON', 'Esperando hinchazón abdominal'), ('ESPERANDO_FRECUENCIA_CARDIACA', 'Esperando frecuencia cardíaca'), ('ESPERANDO_FRECUENCIA_RESPIRATORIA', 'Esperando frecuencia respiratoria'), ('ESPERANDO_TOLERANCIA_LIQUIDOS', 'Esperando tolerancia a líquidos'), ('COMPLETADO', 'Completado')], default='INICIO', max_length=40),
        ),
    ]
