# Generated by Django 6.0.5 on 2026-06-24 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0008_conversacionwhatsapp_temp_frecuencia_respiratoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='medico_responsable',
        ),
        migrations.AddField(
            model_name='paciente',
            name='medico_responsable',
            field=models.ForeignKey(
                blank=True,
                help_text='Usuario del sistema (médico) responsable del paciente. Debe existir como usuario en Django Admin.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='pacientes',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
