# Generated by Django 6.0.5 on 2026-06-25 17:06
# B4: índice B-tree + índice funcional de expresión de zona horaria para los
# filtros fecha_registro__date del alert_engine.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0009_medico_responsable_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodiario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        # Índice funcional sobre la expresión que genera Django con USE_TZ=True
        # + TIME_ZONE=America/Bogota para el operador __date. Sin este índice,
        # el filtro (fecha_registro AT TIME ZONE 'America/Bogota')::date = X
        # fuerza full-table-scan con 10 000+ registros.
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS registrodiario_fecha_local_date_idx "
                "ON signos_sintomas_registrodiario "
                "(CAST(fecha_registro AT TIME ZONE 'America/Bogota' AS date));"
            ),
            reverse_sql=(
                "DROP INDEX IF EXISTS registrodiario_fecha_local_date_idx;"
            ),
        ),
    ]
