# Generated by Django 6.0.5 on 2026-06-25 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0010_b4_fecha_registro_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['SEPSIS', 'FUGA_ANASTOMOTICA', 'ILEO_PARALITICO', 'DOLOR_AGUDO', 'INTOLERANCIA_ORAL', 'TAQUICARDIA'])), name='alerta_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.CheckConstraint(condition=models.Q(('severidad__in', ['ALTA', 'MEDIA', 'BAJA'])), name='alerta_severidad_valida'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_cirugia__isnull', True), ('tipo_cirugia__in', ['sugarbaker_hipec', 'colectomia_electiva', 'otra']), _connector='OR'), name='paciente_tipo_cirugia_valido'),
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.CheckConstraint(condition=models.Q(('aspecto_drenaje__in', ['seroso', 'hematico', 'turbio', 'purulento', 'fecaloide', 'sin_drenaje'])), name='registrodiario_aspecto_drenaje_valido'),
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_drenaje__isnull', True), ('cantidad_drenaje__in', ['poco', 'normal', 'mucho', 'sin_drenaje']), _connector='OR'), name='registrodiario_cantidad_drenaje_valido'),
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.CheckConstraint(condition=models.Q(('hinchazon_abdominal__isnull', True), ('hinchazon_abdominal__in', ['nada', 'algo', 'mucho']), _connector='OR'), name='registrodiario_hinchazon_abdominal_valido'),
        ),
    ]
