# Generated by Django 6.0.6 on 2026-06-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0011_c2_check_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dia', models.DateField(help_text='Día calendario del evento. Se congela al crear — no se recalcula en save().')),
                ('orden', models.PositiveSmallIntegerField(help_text='Posición del check-in en el día: 1=mañana, 2=tarde. Clave robusta del sistema.')),
                ('etiqueta', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde')], help_text='Etiqueta legible para el médico. La fija el scheduler al crear el evento.', max_length=10)),
                ('hora_programada', models.DateTimeField(help_text='Momento en que el sistema disparó (o debía disparar) el prompt al paciente.')),
                ('fecha_respuesta', models.DateTimeField(blank=True, help_text='Momento en que el paciente completó el flujo. null = aún no respondió.', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('NO_RESPONDIDO', 'No respondido')], default='PENDIENTE', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='signos_sintomas.paciente')),
                ('registro', models.OneToOneField(blank=True, help_text='RegistroDiario creado al completar el flujo. Se vincula en transacción atómica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin', to='signos_sintomas.registrodiario')),
            ],
            options={
                'verbose_name': 'Check-in Programado',
                'verbose_name_plural': 'Check-ins Programados',
                'ordering': ['fecha_dia', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('paciente', 'fecha_dia', 'orden'), name='unique_checkin_paciente_dia_orden'), models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'COMPLETADO', 'NO_RESPONDIDO'])), name='checkin_estado_valido'), models.CheckConstraint(condition=models.Q(('etiqueta__in', ['MAÑANA', 'TARDE'])), name='checkin_etiqueta_valida')],
            },
        ),
    ]
