# Generated by Django 6.0.6 on 2026-06-27 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0012_checkin_programado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alerta',
            name='alerta_tipo_valido',
        ),
        migrations.AlterField(
            model_name='alerta',
            name='registro_origen',
            field=models.ForeignKey(blank=True, help_text='El registro diario que disparó esta alerta. Null para alertas SILENCIO (sin respuesta).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='signos_sintomas.registrodiario'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('SEPSIS', 'Fiebre — Riesgo de Sepsis'), ('FUGA_ANASTOMOTICA', 'Drenaje Anormal — Posible Fuga Anastomótica'), ('ILEO_PARALITICO', 'Sin Tránsito Intestinal — Posible Íleo Paralítico'), ('DOLOR_AGUDO', 'Dolor Agudo Incontrolable'), ('INTOLERANCIA_ORAL', 'Intolerancia a Líquidos — Riesgo de Deshidratación'), ('TAQUICARDIA', 'Frecuencia Cardíaca Elevada — Taquicardia'), ('SILENCIO', 'Paciente Sin Respuesta — Check-in No Completado')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['SEPSIS', 'FUGA_ANASTOMOTICA', 'ILEO_PARALITICO', 'DOLOR_AGUDO', 'INTOLERANCIA_ORAL', 'TAQUICARDIA', 'SILENCIO'])), name='alerta_tipo_valido'),
        ),
    ]
