# Generated by Django 6.0.6 on 2026-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0013_bloque4_silencio_registro_origen_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(help_text='Número de documento de identidad — identificador principal del paciente (P-4, decisión 01/07/2026). Obligatorio para pacientes nuevos; null solo permitido en registros previos a esta versión.', max_length=20, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
