# Generated by Django 6.0.6 on 2026-07-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0014_paciente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(blank=True, help_text='Número de documento de identidad — identificador principal del paciente (P-4, decisión 01/07/2026). Obligatorio para pacientes nuevos (exigido por clean(), A-2); null solo permitido en registros previos a esta versión. blank=True a nivel de campo porque full_clean() no debe fallar para pacientes existentes sin cédula — la exigencia para pacientes nuevos vive en clean().', max_length=20, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
