# Generated by Django 6.0.6 on 2026-07-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0015_paciente_cedula_blank_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='consentimiento_informado',
            field=models.BooleanField(default=False, help_text='El paciente autorizó el tratamiento de sus datos de salud (Ley 1581/2012). Marcar solo después de obtener la firma física del formato de consentimiento. Desmarcar si el paciente revoca su autorización.', verbose_name='Consentimiento informado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_consentimiento',
            field=models.DateTimeField(blank=True, help_text='Se registra automáticamente al marcar el consentimiento informado.', null=True, verbose_name='Fecha de consentimiento'),
        ),
    ]
