# Generated by Django 6.0.6 on 2026-07-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0016_paciente_consentimiento_informado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='motivo_resolucion',
            field=models.CharField(blank=True, choices=[('CONTACTO', 'Atendido — contacté al paciente'), ('URGENCIAS', 'Atendido — derivado a urgencias'), ('MEDICACION', 'Atendido — ajuste de medicación'), ('FP_MEDICION', 'Falso positivo — error de medición del paciente'), ('FP_RANGO', 'Falso positivo — dato fuera de rango esperado'), ('ESPONTANEO', 'Resuelto espontáneamente — sin intervención'), ('OTRO', 'Otro')], help_text='Por qué se marcó esta alerta como resuelta. Útil para ajustar umbrales clínicos con datos reales en el futuro.', max_length=20, null=True, verbose_name='Motivo de resolución'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='motivo_resolucion_detalle',
            field=models.CharField(blank=True, help_text='Solo requerido cuando el motivo es "Otro".', max_length=500, null=True, verbose_name='Detalle del motivo'),
        ),
    ]
