# Generated by Django 6.0.6 on 2026-07-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0017_alerta_motivo_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='fecha_ultima_deteccion',
            field=models.DateTimeField(blank=True, help_text='Último check-in en que se volvió a detectar el problema. fecha_alerta = primera detección; esta = la más reciente.', null=True, verbose_name='Última detección'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='veces',
            field=models.PositiveSmallIntegerField(default=1, help_text='En cuántos check-ins se ha detectado este problema mientras la alerta sigue abierta (contador de recurrencia). 1 = primera vez.', verbose_name='Detecciones'),
        ),
    ]
