# Generated by Django 6.0.6 on 2026-07-18 19:53

import django.utils.timezone
from django.db import migrations, models
from django.db.models.functions import Coalesce


def preparar_datos_para_integridad(apps, schema_editor):
    Alerta = apps.get_model('signos_sintomas', 'Alerta')
    CheckInProgramado = apps.get_model('signos_sintomas', 'CheckInProgramado')
    RegistroDiario = apps.get_model('signos_sintomas', 'RegistroDiario')

    # Repara los registros históricos afectados por el cálculo con "hoy".
    # El valor correcto se deriva de datos persistidos, sin inferencia clínica.
    registros_corregidos = []
    queryset = RegistroDiario.objects.select_related('paciente').all()
    for registro in queryset.iterator(chunk_size=500):
        fecha_referencia = django.utils.timezone.localdate(registro.fecha_registro)
        pod = max(0, (fecha_referencia - registro.paciente.fecha_cirugia).days)
        if registro.dia_postoperatorio != pod:
            registro.dia_postoperatorio = pod
            registros_corregidos.append(registro)
    if registros_corregidos:
        RegistroDiario.objects.bulk_update(
            registros_corregidos,
            ['dia_postoperatorio'],
            batch_size=500,
        )

    # Antes de Sprint 5 era posible cerrar alertas sin capturar motivo o fecha.
    # Se conserva su estado y se etiqueta explícitamente como dato histórico;
    # no se inventa una actuación clínica.
    Alerta.objects.filter(
        resuelta=True,
        motivo_resolucion__isnull=True,
    ).update(motivo_resolucion='LEGACY')
    Alerta.objects.filter(
        resuelta=True,
        fecha_resolucion__isnull=True,
    ).update(
        fecha_resolucion=Coalesce('fecha_ultima_deteccion', 'fecha_alerta'),
    )
    Alerta.objects.filter(veces__lt=1).update(veces=1)
    Alerta.objects.filter(
        motivo_resolucion='OTRO',
        motivo_resolucion_detalle__isnull=True,
    ).update(motivo_resolucion_detalle='Detalle no capturado en registro histórico.')
    Alerta.objects.filter(
        motivo_resolucion='OTRO',
        motivo_resolucion_detalle='',
    ).update(motivo_resolucion_detalle='Detalle no capturado en registro histórico.')

    # El scheduler define de forma cerrada 1=mañana y 2=tarde. Se corrigen
    # etiquetas antiguas, pero un orden desconocido detiene la migración para
    # evitar asignarlo silenciosamente al turno equivocado.
    invalidos = CheckInProgramado.objects.exclude(orden__in=[1, 2]).count()
    if invalidos:
        raise RuntimeError(
            f'Hay {invalidos} check-in(s) con orden distinto de 1/2; '
            'requieren revisión manual antes de aplicar esta migración.'
        )
    CheckInProgramado.objects.filter(orden=1).update(etiqueta='MAÑANA')
    CheckInProgramado.objects.filter(orden=2).update(etiqueta='TARDE')


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0018_alerta_fecha_ultima_deteccion_alerta_veces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='motivo_resolucion',
            field=models.CharField(blank=True, choices=[('CONTACTO', 'Atendido — contacté al paciente'), ('URGENCIAS', 'Atendido — derivado a urgencias'), ('MEDICACION', 'Atendido — ajuste de medicación'), ('FP_MEDICION', 'Falso positivo — error de medición del paciente'), ('FP_RANGO', 'Falso positivo — dato fuera de rango esperado'), ('ESPONTANEO', 'Resuelto espontáneamente — sin intervención'), ('OTRO', 'Otro'), ('LEGACY', 'Registro histórico — motivo no capturado')], help_text='Por qué se marcó esta alerta como resuelta. Útil para ajustar umbrales clínicos con datos reales en el futuro.', max_length=20, null=True, verbose_name='Motivo de resolución'),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='fecha_registro',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.RunPython(
            preparar_datos_para_integridad,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.CheckConstraint(condition=models.Q(('veces__gte', 1)), name='alerta_veces_positivo'),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.CheckConstraint(condition=models.Q(('motivo_resolucion__isnull', True), ('motivo_resolucion__in', ['CONTACTO', 'URGENCIAS', 'MEDICACION', 'FP_MEDICION', 'FP_RANGO', 'ESPONTANEO', 'OTRO', 'LEGACY']), _connector='OR'), name='alerta_motivo_resolucion_valido'),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.CheckConstraint(condition=models.Q(('resuelta', False), models.Q(('fecha_resolucion__isnull', False), ('motivo_resolucion__isnull', False)), _connector='OR'), name='alerta_resuelta_con_cierre'),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('motivo_resolucion', 'OTRO'), _negated=True), models.Q(('motivo_resolucion_detalle__isnull', False), models.Q(('motivo_resolucion_detalle', ''), _negated=True)), _connector='OR'), name='alerta_otro_con_detalle'),
        ),
        migrations.AddConstraint(
            model_name='checkinprogramado',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('etiqueta', 'MAÑANA'), ('orden', 1)), models.Q(('etiqueta', 'TARDE'), ('orden', 2)), _connector='OR'), name='checkin_turno_coherente'),
        ),
    ]
