# Generated by Django 6.0.6 on 2026-07-18 23:00

from django.db import migrations, models
from django.db.models import Count
from django.utils import timezone


def preparar_datos_para_garantias_loop_2(apps, schema_editor):
    RegistroDiario = apps.get_model('signos_sintomas', 'RegistroDiario')
    Alerta = apps.get_model('signos_sintomas', 'Alerta')

    # Los registros previos ya pasaron por el motor con la implementación
    # existente. Marcarlos como completados evita reanalizarlos al desplegar.
    RegistroDiario.objects.update(estado_evaluacion_alertas='COMPLETADA')

    duplicados = (
        Alerta.objects.filter(resuelta=False)
        .values('paciente_id', 'tipo')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )
    prioridad_severidad = {'BAJA': 1, 'MEDIA': 2, 'ALTA': 3}

    for grupo in duplicados.iterator():
        alertas = list(
            Alerta.objects.filter(
                paciente_id=grupo['paciente_id'],
                tipo=grupo['tipo'],
                resuelta=False,
            ).order_by('fecha_alerta', 'id')
        )
        principal = alertas[0]
        fecha_mas_reciente = max(
            alerta.fecha_ultima_deteccion or alerta.fecha_alerta
            for alerta in alertas
        )
        alerta_mas_reciente = max(
            alertas,
            key=lambda alerta: alerta.fecha_ultima_deteccion or alerta.fecha_alerta,
        )
        alerta_mas_severa = max(
            alertas,
            key=lambda alerta: prioridad_severidad.get(alerta.severidad, 0),
        )
        principal.veces = sum(alerta.veces for alerta in alertas)
        principal.severidad = alerta_mas_severa.severidad
        principal.fecha_ultima_deteccion = fecha_mas_reciente
        principal.registro_origen_id = alerta_mas_reciente.registro_origen_id
        principal.mensaje = alerta_mas_severa.mensaje
        principal.save(update_fields=[
            'veces',
            'severidad',
            'fecha_ultima_deteccion',
            'registro_origen_id',
            'mensaje',
        ])

        Alerta.objects.filter(pk__in=[alerta.pk for alerta in alertas[1:]]).update(
            resuelta=True,
            fecha_resolucion=timezone.now(),
            motivo_resolucion='LEGACY',
            motivo_resolucion_detalle=(
                'Consolidada técnicamente al activar la unicidad de alertas abiertas.'
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0019_alter_alerta_motivo_resolucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionWebhookTwilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(max_length=64, unique=True)),
                ('idempotency_token', models.CharField(blank=True, default='', max_length=128)),
                ('estado', models.CharField(choices=[('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error; admite reintento')], db_index=True, default='PROCESANDO', max_length=12)),
                ('intentos', models.PositiveSmallIntegerField(default=1)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recepción webhook Twilio',
                'verbose_name_plural': 'Recepciones webhook Twilio',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='estado_evaluacion_alertas',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error; requiere reintento')], db_index=True, default='PENDIENTE', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='fecha_ultima_evaluacion_alertas',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='intentos_evaluacion_alertas',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='ultimo_error_evaluacion_alertas',
            field=models.CharField(blank=True, default='', editable=False, help_text='Solo conserva el tipo de error; nunca respuestas del paciente.', max_length=100),
        ),
        migrations.RunPython(
            preparar_datos_para_garantias_loop_2,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(condition=models.Q(('resuelta', False)), fields=('paciente', 'tipo'), name='unique_alerta_abierta_paciente_tipo'),
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.CheckConstraint(condition=models.Q(('estado_evaluacion_alertas__in', ['PENDIENTE', 'PROCESANDO', 'COMPLETADA', 'ERROR'])), name='registro_estado_evaluacion_valido'),
        ),
        migrations.AddConstraint(
            model_name='recepcionwebhooktwilio',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PROCESANDO', 'COMPLETADO', 'ERROR'])), name='webhook_twilio_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='recepcionwebhooktwilio',
            constraint=models.CheckConstraint(condition=models.Q(('intentos__gte', 1)), name='webhook_twilio_intentos_positivo'),
        ),
    ]
