# Generated by Django 6.0.6 on 2026-07-18 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0020_recepcionwebhooktwilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='checkin_actual',
            field=models.OneToOneField(blank=True, editable=False, help_text='Check-in exacto cuyas respuestas se están recolectando.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversacion_activa', to='signos_sintomas.checkinprogramado'),
        ),
    ]
