# Generated by Django 6.0.6 on 2026-07-19 06:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0021_conversacionwhatsapp_checkin_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeteccionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severidad_detectada', models.CharField(choices=[('ALTA', 'Alta — Ir a urgencias'), ('MEDIA', 'Media — Llamar al médico'), ('BAJA', 'Baja — Monitorear')], max_length=10)),
                ('mensaje_detectado', models.TextField(help_text='Copia del mensaje clínico generado para esta detección.')),
                ('fecha_deteccion', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de detección')),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detecciones', to='signos_sintomas.alerta')),
                ('checkin', models.ForeignKey(blank=True, help_text='Check-in no respondido que produjo una alerta de silencio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detecciones_alerta', to='signos_sintomas.checkinprogramado')),
                ('registro', models.ForeignKey(blank=True, help_text='Registro clínico que produjo la detección.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detecciones_alerta', to='signos_sintomas.registrodiario')),
            ],
            options={
                'verbose_name': 'Detección de alerta',
                'verbose_name_plural': 'Detecciones registradas desde Loop 3',
                'ordering': ['-fecha_deteccion', '-pk'],
                'indexes': [models.Index(fields=['alerta', '-fecha_deteccion'], name='deteccion_alerta_fecha_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('checkin__isnull', True), ('registro__isnull', False)), models.Q(('checkin__isnull', False), ('registro__isnull', True)), _connector='OR'), name='deteccion_fuente_unica'), models.CheckConstraint(condition=models.Q(('severidad_detectada__in', ['ALTA', 'MEDIA', 'BAJA'])), name='deteccion_severidad_valida'), models.UniqueConstraint(condition=models.Q(('registro__isnull', False)), fields=('alerta', 'registro'), name='unique_det_alerta_registro'), models.UniqueConstraint(condition=models.Q(('checkin__isnull', False)), fields=('alerta', 'checkin'), name='unique_det_alerta_checkin')],
            },
        ),
    ]
