# Generated by Django 6.0.6 on 2026-07-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0022_deteccionalerta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deteccionalerta',
            options={'ordering': ['-fecha_deteccion', '-pk'], 'verbose_name': 'Detección de alerta', 'verbose_name_plural': 'Detecciones de alerta'},
        ),
    ]
