# Generated by Django 6.0.7 on 2026-07-20 01:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0023_alter_deteccionalerta_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(blank=True, default='', max_length=254)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada')], db_index=True, default='PENDIENTE', max_length=10)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('proximo_intento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.CharField(blank=True, default='', max_length=100)),
                ('alerta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='notificacion_email', to='signos_sintomas.alerta')),
            ],
            options={
                'verbose_name': 'Notificación de alerta',
                'verbose_name_plural': 'Notificaciones de alertas',
                'ordering': ['proximo_intento', 'pk'],
                'indexes': [models.Index(fields=['estado', 'proximo_intento'], name='notif_estado_proximo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'ENVIADA'])), name='notificacion_alerta_estado_valido'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'PENDIENTE'), ('fecha_envio__isnull', True)), models.Q(('estado', 'ENVIADA'), ('fecha_envio__isnull', False)), _connector='OR'), name='notificacion_alerta_envio_coherente')],
            },
        ),
    ]
