# Generated by Django 6.0.7 on 2026-07-24 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0024_notificacion_alerta_outbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='resuelta_por',
            field=models.ForeignKey(blank=True, help_text='Médico que marcó esta alerta como resuelta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por'),
        ),
    ]
