# Generated by Django 6.0.7 on 2026-07-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0025_alerta_resuelta_por'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificacionalerta',
            name='notificacion_alerta_estado_valido',
        ),
        migrations.RemoveConstraint(
            model_name='notificacionalerta',
            name='notificacion_alerta_envio_coherente',
        ),
        migrations.AlterField(
            model_name='notificacionalerta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida')], db_index=True, default='PENDIENTE', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='notificacionalerta',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'ENVIADA', 'FALLIDA'])), name='notificacion_alerta_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='notificacionalerta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'PENDIENTE'), ('fecha_envio__isnull', True)), models.Q(('estado', 'ENVIADA'), ('fecha_envio__isnull', False)), models.Q(('estado', 'FALLIDA'), ('fecha_envio__isnull', True)), _connector='OR'), name='notificacion_alerta_envio_coherente'),
        ),
    ]
