# Generated by Django 6.0.7 on 2026-07-28 02:34

from django.conf import settings
"""D12 (capa 4) — activo ⇒ medico_responsable no nulo.

SQL: ALTER TABLE ... ADD CONSTRAINT ... CHECK (NOT activo OR
medico_responsable_id IS NOT NULL).

ESTA MIGRACIÓN SÍ TOCA LA BASE, y Postgres valida TODAS las filas existentes al
crear la restricción. Si alguna la violara, `migrate` falla — y como el
Dockerfile encadena `migrate --noinput && gunicorn`, eso no es un error en el
log: es el contenedor sin arrancar.

Por eso el Loop D empezó por la compuerta D-0, una consulta de solo lectura
contra producción. Resultado del 27/07/2026: 2 pacientes, 0 activos, cero
activos sin responsable. Ninguna fila puede violarla.

Antes de aplicarla en otro entorno, volver a contar:
    SELECT COUNT(*) FROM signos_sintomas_paciente
     WHERE activo AND medico_responsable_id IS NULL;   -- debe dar 0
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0027_alter_paciente_medico_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.CheckConstraint(condition=models.Q(('activo', False), ('medico_responsable__isnull', False), _connector='OR'), name='paciente_activo_con_medico_responsable'),
        ),
    ]
