# Generated by Django 6.0.8 on 2026-09-08 16:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0028_paciente_paciente_activo_con_medico_responsable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checkinprogramado',
            name='checkin_estado_valido',
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('SEPSIS', 'Fiebre — Riesgo de Sepsis'), ('FUGA_ANASTOMOTICA', 'Drenaje Anormal — Posible Fuga Anastomótica'), ('ILEO_PARALITICO', 'Sin Tránsito Intestinal — Posible Íleo Paralítico'), ('DOLOR_AGUDO', 'Dolor Agudo Incontrolable'), ('INTOLERANCIA_ORAL', 'Intolerancia a Líquidos — Riesgo de Deshidratación'), ('TAQUICARDIA', 'Frecuencia Cardíaca Elevada — Taquicardia'), ('SILENCIO', 'Paciente Sin Respuesta — Check-in No Completado'), ('AUXILIO', 'Petición de Auxilio del Paciente')], max_length=30),
        ),
        migrations.AlterField(
            model_name='checkinprogramado',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('NO_RESPONDIDO', 'No respondido'), ('SIN_CONSENTIMIENTO', 'Detenido — sin consentimiento')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='dolor_eva',
            field=models.PositiveSmallIntegerField(help_text='Escala visual análoga del 0 al 10. 0 = sin dolor (D20)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='episodios_nauseas',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número de episodios de náuseas o vómito en 24h', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='frecuencia_cardiaca',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Frecuencia cardíaca en lpm. null = no capturado. Solo se vigila taquicardia (FC alta), no bradicardia.', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='frecuencia_respiratoria',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Frecuencia respiratoria en rpm. null = no capturado. SOLO DASHBOARD — no genera alerta (Outersterp 2025: 77% de falsas alertas provenían del sensor de FR).', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura corporal en °C. Ej: 37.5. null = el paciente no pudo medirla y saltó la pregunta (decisión D20); la Regla 1 no se evalúa en ese caso.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30.0')), django.core.validators.MaxValueValidator(Decimal('45.0'))]),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='volumen_drenaje_ml',
            field=models.PositiveIntegerField(blank=True, help_text='Volumen en ml — OPCIONAL, solo si el paciente lo midió', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddConstraint(
            model_name='checkinprogramado',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'COMPLETADO', 'NO_RESPONDIDO', 'SIN_CONSENTIMIENTO'])), name='checkin_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.CheckConstraint(condition=models.Q(('temperatura__isnull', True), models.Q(('temperatura__gte', Decimal('30.0')), ('temperatura__lte', Decimal('45.0'))), _connector='OR'), name='registro_temperatura_en_rango'),
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.CheckConstraint(condition=models.Q(('dolor_eva__gte', 0), ('dolor_eva__lte', 10)), name='registro_dolor_eva_en_rango'),
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.CheckConstraint(condition=models.Q(('episodios_nauseas__gte', 0), ('episodios_nauseas__lte', 20)), name='registro_episodios_nauseas_en_rango'),
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.CheckConstraint(condition=models.Q(('frecuencia_cardiaca__isnull', True), models.Q(('frecuencia_cardiaca__gte', 30), ('frecuencia_cardiaca__lte', 250)), _connector='OR'), name='registro_frecuencia_cardiaca_en_rango'),
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.CheckConstraint(condition=models.Q(('frecuencia_respiratoria__isnull', True), models.Q(('frecuencia_respiratoria__gte', 5), ('frecuencia_respiratoria__lte', 60)), _connector='OR'), name='registro_frecuencia_respiratoria_en_rango'),
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.CheckConstraint(condition=models.Q(('volumen_drenaje_ml__isnull', True), ('volumen_drenaje_ml__lte', 5000), _connector='OR'), name='registro_volumen_drenaje_en_rango'),
        ),
    ]
