# Generated by Django 6.0.8 on 2026-09-08 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0029_rangos_clinicos_auxilio_y_consentimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alerta',
            name='alerta_tipo_valido',
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['SEPSIS', 'FUGA_ANASTOMOTICA', 'ILEO_PARALITICO', 'DOLOR_AGUDO', 'INTOLERANCIA_ORAL', 'TAQUICARDIA', 'SILENCIO', 'AUXILIO'])), name='alerta_tipo_valido'),
        ),
    ]
