# Generated by Django 6.1.1 on 2026-10-02 18:08
#
# UX-B03 (loop del 02/10/2026): la pregunta de gases y náuseas se parte en dos.
# Una conversación que estuviera esperando la respuesta combinada pasa a
# esperar la de gases, que es la primera de las dos: el paciente vuelve a ver
# esa pregunta y no se pierde nada, porque en ese estado aún no había guardado
# ninguno de los dos datos.
#
# El reverso es real y no un `noop` (hallazgo DB-10): las dos esperas nuevas
# vuelven a la combinada, y se descarta el dato de gases que se hubiera
# anotado, porque el estado viejo pide los dos a la vez.

from django.db import migrations, models

VIEJO = 'ESPERANDO_GASES_NAUSEAS'
GASES = 'ESPERANDO_GASES'
NAUSEAS = 'ESPERANDO_NAUSEAS'


def partir(apps, schema_editor):
    Conversacion = apps.get_model('signos_sintomas', 'ConversacionWhatsApp')
    Conversacion.objects.filter(estado=VIEJO).update(estado=GASES)


def juntar(apps, schema_editor):
    Conversacion = apps.get_model('signos_sintomas', 'ConversacionWhatsApp')
    Conversacion.objects.filter(estado__in=[GASES, NAUSEAS]).update(
        estado=VIEJO,
        temp_presencia_gases=None,
        temp_episodios_nauseas=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('signos_sintomas', '0030_tipo_alerta_auxilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='estado',
            field=models.CharField(choices=[('INICIO', 'Inicio'), ('ESPERANDO_TEMPERATURA', 'Esperando temperatura'), ('ESPERANDO_DOLOR', 'Esperando dolor EVA'), ('ESPERANDO_TIENE_DRENAJE', 'Esperando si tiene drenaje'), ('ESPERANDO_ASPECTO_DRENAJE', 'Esperando aspecto del drenaje'), ('ESPERANDO_CANTIDAD_DRENAJE', 'Esperando cantidad del drenaje'), ('ESPERANDO_GASES', 'Esperando gases'), ('ESPERANDO_NAUSEAS', 'Esperando náuseas'), ('ESPERANDO_HINCHAZON', 'Esperando hinchazón abdominal'), ('ESPERANDO_FRECUENCIA_CARDIACA', 'Esperando frecuencia cardíaca'), ('ESPERANDO_FRECUENCIA_RESPIRATORIA', 'Esperando frecuencia respiratoria'), ('ESPERANDO_TOLERANCIA_LIQUIDOS', 'Esperando tolerancia a líquidos'), ('COMPLETADO', 'Completado')], default='INICIO', max_length=40),
        ),
        migrations.RunPython(partir, reverse_code=juntar),
    ]
