# Generated by Django 6.0.5 on 2026-06-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'mensaje de contacto',
                'verbose_name_plural': 'mensajes de contacto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
