# Generated by Django 6.0.6 on 2026-07-19 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='medico_destinatario',
            field=models.ForeignKey(blank=True, help_text='Médico que puede consultar y marcar este mensaje. Sin asignar significa visible solo para el superusuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_contacto', to=settings.AUTH_USER_MODEL, verbose_name='Médico destinatario'),
        ),
    ]
