# Generated by Django 6.0.8 on 2026-09-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mensajecontacto_medico_destinatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='autorizacion_datos',
            field=models.BooleanField(default=False, help_text='Marcada por la persona en el formulario público. Sin ella el envío se rechaza (Ley 1581/2012, art. 6).', verbose_name='Autorizó el tratamiento de sus datos'),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, help_text='Momento en que se marcó la casilla. Es la prueba de la autorización.', null=True, verbose_name='Fecha de la autorización'),
        ),
    ]
